machine: "cluster"  # or "cluster"
device: "cuda"  # or "cpu"
anomaly_detection: False  # slows down the code
mode: autoencoder  # 'gan' or 'regression' or 'figures' or 'embedding' or 'sampling' WIP
dataset_name: 'dataset.pkl'
misc_dataset_name: 'misc_data_for_dataset.npy'
dataset_yaml_path: '/dataset/small_autoencoder.yaml'
extra_test_set_name: null #'test_blind_test_dataset.pkl'  #'acridin_dataset.pkl' #'test_blind_test_dataset.pkl'
save_checkpoints: True # will do it always on cluster, only locally if True

dataset:
  max_dataset_length: 1000000

# batching & convergence
early_epochs_step_override: 100
num_early_epochs: 10
grow_batch_size: True
min_batch_size: 100
max_batch_size: 10000
batch_growth_increment: 0.1 # fraction of batch size to grow by each epoch
max_epochs: 100000 # 0 epochs takes us straight to sampling/evaluation (only implemented for GAN)
history: 5000  # for convergence checks
gradient_norm_clip: 1
extra_test_period: 1 # # MUST BE MULTIPLE OF SAMPLE REPORTING FREQUENCY how often to evaluate on extra test sets (hardcoded analysis per extra test set)

logger:
  run_name: autoencoder_m2
  mini_csp_frequency: 5
  sample_reporting_frequency: 10
  log_figures: True
  experiment_tag: autoencoder_battery1

sample_steps: 100 

seeds:
  model: 1
  dataset: 0

# for reloading prior checkpoints
model_paths:
  discriminator: null
  generator: null
  regressor: null
  proxy_discriminator: null
  autoencoder: null

discriminator_positional_noise: 0
generator_positional_noise: 0
regressor_positional_noise: 0
autoencoder_positional_noise: 0.1

generate_sgs: null  #["P-1","P21/c","P212121","C2/c"] # null -> will generate in original sg.  'all' -> will randomly pick between all possibilities. []
supercell_size: 5
# for GAN training
generator:
  # settings
  canonical_conformer_orientation: 'random' # 'standardized' 'random'
  packing_target_noise: 0.05 # randn noise magnitude in the standardized basis
  train_vdw: False
  train_adversarially: False
  vdw_loss_func: inv  # null 'mse' or 'log' or 'inv'
  density_loss_func: l1  # 'l1' or 'mse'
  adversarial_loss_func: 'score'  #
  train_h_bond: False # (non-directional)
  similarity_penalty: 0.5

  #generator optimizer and model
  optimizer:
    optimizer: adamw
    init_lr: 1.0E-4
    max_lr: 1.0E-3
    min_lr: 1.0E-4
    lr_schedule: True
    beta1: 0.9 #0.9
    beta2: 0.999 #0.999
    weight_decay: 0.01
    convergence_eps: 0.00001
    lr_growth_lambda: 1.05
    lr_shrink_lambda: 0.99

  model:
    num_fc_layers: 2
    fc_depth: 128
    activation: 'gelu'
    fc_dropout_probability: 0.1
    fc_norm_mode: layer
    conditioning_mode: 'first_layer' # 'first_layer' only for now

    prior: multivariate normal
    prior_dimension: 12  # NOTE this must be 12 currently
    radial_norm_factor: 5

    conditioner:
      graph_convolution_type: TransformerConv
      graph_aggregator: combo
      concat_mol_to_atom_features: False
      activation: gelu
      num_fc_layers: 4
      fc_depth: 256
      fc_norm_mode: layer
      fc_dropout_probability: 0.1
      graph_node_norm: 'graph layer'
      graph_node_dropout: 0.1
      graph_message_norm: null
      graph_message_dropout: 0
      num_attention_heads: 4
      graph_message_depth: 64
      graph_node_dims: 256
      num_graph_convolutions: 2
      graph_embedding_depth: 256
      nodewise_fc_layers: 1
      num_radial: 50
      radial_function: gaussian
      max_num_neighbors: 100
      convolution_cutoff: 6
      atom_type_embedding_dims: 5

discriminator:
  # settings
  train_adversarially: False
  train_on_randn: True
  train_on_distorted: True
  use_classification_loss: True
  use_rdf_distance_loss: True
  use_cell_distance_loss: False  # DO NOT USE only meaningful when generating within the same space group
  distortion_magnitude: -1 # -1 for wide range test # noise for distorted generation

  # discriminator optimizer and model
  optimizer:
    optimizer: adamw
    init_lr: 1.0E-5
    max_lr: 2.0E-4
    min_lr: 1.0E-4
    lr_schedule: True
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.001
    convergence_eps: 0.00001
    training_period: 1
    lr_growth_lambda: 1.05
    lr_shrink_lambda: 0.99

  model:
    graph_convolution_type: TransformerConv
    graph_aggregator:  combo
    concat_mol_to_atom_features: True
    activation: gelu
    num_fc_layers: 2
    fc_depth: 128
    fc_norm_mode: layer
    fc_dropout_probability: 0.25
    graph_node_norm: 'graph layer'
    graph_node_dropout: 0.25
    graph_message_norm: null
    graph_message_dropout: 0
    num_attention_heads: 4
    graph_message_depth: 128
    graph_node_dims: 256
    num_graph_convolutions: 4
    graph_embedding_depth: 256
    nodewise_fc_layers: 1
    num_radial: 32
    radial_function: bessel
    max_num_neighbors: 100
    convolution_cutoff: 6
    atom_type_embedding_dims: 5
    periodic_convolution_type: 'all_layers'  # or 'last_layer'


autoencoder:
  molecule_radius_normalization: 5
  random_fraction: 0
  min_num_atoms: 2
  max_num_atoms: 5
  init_sigma: 0.25
  sigma_lambda: 0.99
  sigma_threshold: 0.01
  overlap_eps: 1.0E-3
  independent_node_weights: False
  node_weight_temperature: 10
  type_distance_scaling: 0.5

  # discriminator optimizer and model
  optimizer:
    optimizer: adamw
    init_lr: 1.0E-4
    max_lr: 1.0E-3
    min_lr: 5.0E-4
    lr_schedule: True
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.001
    convergence_eps: 0.00001
    training_period: 1
    lr_growth_lambda: 1.01
    lr_shrink_lambda: 0.995

  model:
    graph_convolution_type: TransformerConv
    graph_aggregator:  max
    embedding_depth: 512
    concat_mol_to_atom_features: True
    activation: gelu
    num_decoder_layers: 2
    decoder_norm_mode: batch
    decoder_dropout_probability: 0
    graph_node_norm: 'graph layer'
    graph_node_dropout: 0
    graph_message_dropout: 0
    num_attention_heads: 4
    graph_message_depth: 128
    graph_node_dims: 256
    num_graph_convolutions: 4
    graph_embedding_depth: 256
    nodewise_fc_layers: 1
    num_radial: 50
    radial_function: gaussian
    max_num_neighbors: 100
    convolution_cutoff: 2
    atom_type_embedding_dims: 5
    num_decoder_points: 256

proxy_discriminator:
  #settings
  train: False

  # discriminator optimizer and model
  optimizer: null
  model: null

regressor:
  # settings
  optimizer: null
  model: null