anomaly_detection: false
autoencoder:
  independent_node_weights: false
  init_sigma: 0.25
  max_overlap_threshold: 0.18
  model:
    activation: gelu
    atom_type_embedding_dims: 5
    convolution_cutoff: 2
    decoder_dropout_probability: 0
    decoder_norm_mode: batch
    embedding_depth: 512
    graph_aggregator: max
    graph_convolution_type: TransformerConv
    graph_embedding_depth: 512
    graph_message_depth: 512
    graph_message_dropout: 0
    graph_node_dims: 512
    graph_node_dropout: 0
    graph_node_norm: graph layer
    max_num_neighbors: 100
    nodewise_fc_layers: 4
    num_attention_heads: 4
    num_decoder_layers: 4
    num_decoder_points: 256
    num_graph_convolutions: 4
    num_radial: 50
    radial_function: gaussian
  node_weight_temperature: 10
  optimizer:
    beta1: 0.9
    beta2: 0.999
    convergence_eps: 0.0001
    decoder_init_lr: 0.001
    encoder_init_lr: 0.0001
    init_lr: 0.0001
    lr_growth_lambda: 1.0
    lr_schedule: false
    lr_shrink_lambda: 0.995
    max_lr: 1.0e-05
    min_lr: 1.0e-05
    optimizer: adam
    training_period: 1
    use_plateau_scheduler: false
    weight_decay: 0.001
  overlap_eps: 0.001
  random_fraction: 1
  sigma_lambda: 0.99
  sigma_threshold: 0.01
  type_distance_scaling: 0.5
autoencoder_positional_noise: 0
batch_growth_increment: 0.05
dataset:
  filter_conditions:
  - - crystal_z_prime
    - in
    - - 1
  - - molecule_num_atoms
    - range
    - - 3
      - 7
  - - molecule_radius
    - range
    - - 0.1
      - 5
  - - atom_atomic_numbers
    - range
    - - 6
      - 8
  max_dataset_length: 10000
dataset_name: test_dataset.pkl
dataset_yaml_path: /dataset/small_autoencoder.yaml
device: cuda
discriminator:
  distortion_magnitude: -1
  model: null
  optimizer: null
  train_adversarially: true
  train_on_distorted: true
  train_on_randn: true
  use_cell_distance_loss: false
  use_classification_loss: true
  use_rdf_distance_loss: true
discriminator_positional_noise: 0
early_epochs_step_override: 100
extra_test_period: 1
extra_test_set_name: null
generate_sgs: null
generator:
  adversarial_loss_func: score
  canonical_conformer_orientation: random
  density_loss_func: l1
  model: null
  optimizer: null
  packing_target_noise: 0.05
  similarity_penalty: 0
  train_adversarially: true
  train_h_bond: false
  train_vdw: true
  vdw_loss_func: inv
generator_positional_noise: 0
gradient_norm_clip: 1
grow_batch_size: true
history: 200
logger:
  experiment_tag: autoencoder_battery1
  log_figures: true
  mini_csp_frequency: 5
  run_name: base_0_1
  sample_reporting_frequency: 5
machine: cluster
max_batch_size: 1000
max_epochs: 100000
min_batch_size: 2
misc_dataset_name: misc_data_for_dataset.npy
mode: autoencoder
model_paths:
  autoencoder: null
  discriminator: null
  generator: null
  regressor: null
num_early_epochs: 10
regressor:
  model: null
  optimizer: null
regressor_positional_noise: 0
save_checkpoints: false
seeds:
  dataset: 0
  model: 0
supercell_size: 5
