anomaly_detection: false
autoencoder:
  KLD_threshold: 0.95
  KLD_weight: 0.001
  evaluation_sigma: 0.05
  independent_node_weights: true
  infer_protons: false
  init_sigma: 0.15
  max_overlap_threshold: 0.25
  model:
    activation: gelu
    atom_type_embedding_dims: 5
    bottleneck_dim: 256
    convolution_cutoff: 2
    decoder_dropout_probability: 0
    decoder_norm_mode: layer
    decoder_ramp_depth: true
    decoder_type: equivariant
    decoder_vector_norm: vector layer
    embedding_depth: 256
    encoder_type: equivariant
    encoder_vector_norm: graph vector layer
    graph_aggregator: equivariant softmax
    graph_message_depth: 256
    graph_message_dropout: 0
    graph_node_dropout: 0
    graph_node_norm: graph layer
    max_num_neighbors: 100
    nodewise_fc_layers: 4
    num_attention_heads: 16
    num_decoder_layers: 4
    num_decoder_points: 256
    num_graph_convolutions: 1
    num_radial: 32
    radial_function: gaussian
    variational_encoder: false
  node_weight_temperature: 1
  optimizer:
    beta1: 0.9
    beta2: 0.999
    convergence_eps: 1.0e-05
    decoder_init_lr: 5.0e-05
    encoder_init_lr: 5.0e-05
    init_lr: 0.0001
    lr_growth_lambda: 1.01
    lr_schedule: true
    lr_shrink_lambda: 0.999
    max_lr: 0.0001
    min_lr: 5.0e-06
    optimizer: adamw
    use_plateau_scheduler: false
    weight_decay: 0.075
  overlap_eps:
    test: 0.001
  random_fraction: 0
  sigma_lambda: 0.99
  sigma_threshold: 0.01
  type_distance_scaling: 0.5
autoencoder_positional_noise: 0
base_config_path: /experiments/base.yaml
batch_growth_increment: 0.1
checkpointing_loss_type: test
dataset:
  filter_protons: true
  max_dataset_length: 1000000
  regression_target: molecule_rotational_constant_c
  test_fraction: 0.2
dataset_name: qm9_molecules_dataset.pkl
dataset_yaml_path: /dataset/qm9_autoencoder.yaml
device: cuda
discriminator:
  distortion_magnitude: -1
  model:
    activation: gelu
    atom_type_embedding_dims: 24
    concat_mol_to_atom_features: true
    convolution_cutoff: 6
    fc_depth: 256
    fc_dropout_probability: 0.25
    fc_norm_mode: layer
    graph_aggregator: combo
    graph_convolution_type: TransformerConv
    graph_embedding_depth: 256
    graph_message_depth: 128
    graph_message_dropout: 0
    graph_message_norm: null
    graph_node_dims: 256
    graph_node_dropout: 0.25
    graph_node_norm: graph layer
    max_num_neighbors: 100
    nodewise_fc_layers: 1
    num_attention_heads: 16
    num_fc_layers: 4
    num_graph_convolutions: 4
    num_radial: 32
    periodic_convolution_type: all_layers
    radial_function: bessel
  optimizer:
    beta1: 0.9
    beta2: 0.999
    convergence_eps: 0.0001
    init_lr: 0.001
    lr_growth_lambda: 1.0
    lr_schedule: true
    lr_shrink_lambda: 0.995
    max_lr: 1.0e-05
    min_lr: 1.0e-05
    optimizer: adamw
    use_plateau_scheduler: false
    weight_decay: 1
  train_adversarially: false
  train_on_distorted: true
  train_on_randn: true
  use_cell_distance_loss: false
  use_classification_loss: true
  use_rdf_distance_loss: true
discriminator_positional_noise: 0
early_epochs_step_override: 5
embedding_regressor:
  model:
    depth: 256
    dropout: 0.1
    equivariant: true
    norm_mode: layer
    num_layers: 4
    vector_norm: vector layer
  num_targets: 1
  optimizer:
    beta1: 0.9
    beta2: 0.999
    convergence_eps: 1.0e-06
    init_lr: 0.001
    lr_growth_lambda: 1.0
    lr_schedule: true
    lr_shrink_lambda: 0.99
    max_lr: 1.0e-05
    min_lr: 1.0e-05
    optimizer: adamw
    use_plateau_scheduler: false
    weight_decay: 1
  prediction_type: scalar
extra_test_period: 1
extra_test_set_name: null
generate_sgs:
- P-1
generator:
  adversarial_loss_func: score
  canonical_conformer_orientation: random
  density_loss_func: l1
  model:
    activation: gelu
    conditioner:
      activation: gelu
      atom_type_embedding_dims: 5
      concat_mol_to_atom_features: false
      convolution_cutoff: 6
      fc_depth: 256
      fc_dropout_probability: 0.1
      fc_norm_mode: layer
      graph_aggregator: combo
      graph_convolution_type: TransformerConv
      graph_embedding_depth: 256
      graph_message_depth: 64
      graph_message_dropout: 0
      graph_message_norm: null
      graph_node_dims: 256
      graph_node_dropout: 0.1
      graph_node_norm: graph layer
      max_num_neighbors: 100
      nodewise_fc_layers: 1
      num_attention_heads: 4
      num_fc_layers: 4
      num_graph_convolutions: 2
      num_radial: 50
      radial_function: gaussian
    conditioning_mode: first_layer
    fc_depth: 128
    fc_dropout_probability: 0.1
    fc_norm_mode: layer
    num_fc_layers: 2
    prior: multivariate normal
    prior_dimension: 12
    radial_norm_factor: 5
  optimizer:
    beta1: 0.9
    beta2: 0.999
    convergence_eps: 1.0e-05
    init_lr: 0.0005
    lr_growth_lambda: 1.05
    lr_schedule: true
    lr_shrink_lambda: 0.99
    max_lr: 0.001
    min_lr: 0.0001
    optimizer: adamw
    weight_decay: 0.01
  packing_target_noise: 0.05
  similarity_penalty: 0
  train_adversarially: false
  train_h_bond: false
  train_vdw: false
  vdw_loss_func: inv
generator_positional_noise: 0
gradient_norm_clip: 1
grow_batch_size: true
history: 100
logger:
  experiment_tag: qm9r_test5
  log_figures: true
  mini_csp_frequency: 5
  run_name: qm9r_test5_0_1_2_3_4_5
  sample_reporting_frequency: 3
machine: cluster
max_batch_size: 10000
max_epochs: 100000
min_batch_size: 25
minimum_epochs: 1000
misc_dataset_name: misc_data_for_qm9_molecules_dataset.npy
mode: embedding_regression
model_names:
- autoencoder
- embedding_regressor
model_paths:
  autoencoder: null
  discriminator: null
  embedding_regressor: best_autoencoder_autoencoder_tests_qm9_test21_20_13-02-10-13-47
  generator: null
  regressor: null
num_early_epochs: 0
overfit_tolerance: 4
regressor:
  model:
    activation: gelu
    atom_type_embedding_dims: 5
    concat_mol_to_atom_features: true
    convolution_cutoff: 6
    fc_depth: 512
    fc_dropout_probability: 0
    fc_norm_mode: null
    graph_aggregator: softmax
    graph_convolution_type: TransformerConv
    graph_embedding_depth: 512
    graph_message_depth: 128
    graph_message_dropout: 0
    graph_message_norm: null
    graph_node_dims: 512
    graph_node_dropout: 0
    graph_node_norm: null
    max_num_neighbors: 100
    nodewise_fc_layers: 1
    num_attention_heads: 32
    num_fc_layers: 4
    num_graph_convolutions: 4
    num_radial: 32
    radial_function: bessel
  optimizer:
    beta1: 0.9
    beta2: 0.999
    convergence_eps: 1.0e-05
    decoder_init_lr: 0.001
    encoder_init_lr: 0.0005
    init_lr: 0.0001
    lr_growth_lambda: 1.0
    lr_schedule: true
    lr_shrink_lambda: 0.999
    max_lr: 1.0e-05
    min_lr: 5.0e-05
    optimizer: adamw
    use_plateau_scheduler: false
    weight_decay: 0.075
regressor_positional_noise: 0
sample_steps: 100
save_checkpoints: true
seeds:
  dataset: 0
  model: 12345
supercell_size: 5
sweep_id: null
sweep_path: null
