#First, define the dataset by a series of conditions in format [key, type, [elements]]
#where type is in not_in or range and elements are [min, max], or a list of discrete values
#
#Then, specify the features which will be fed to models in training

seed: 1
max_dataset_length: 1000000
save_dataset: False

regression_target: 'crystal_packing_coefficient' # 'crystal_reduced_cell_volume' 'crystal_density' 'crystal_packing_coefficient'
single_molecule_dataset_identifier: null
test_fraction: 0.2

filter_polymorphs: True
filter_duplicate_molecules: True
filter_conditions: [['crystal_z_prime','in',[1]],
                    ['molecule_num_atoms','range',[3, 30]],
                    ['molecule_radius','range',[0.1, 8]],
                    ['atom_atomic_numbers','range', [6, 9]]
                    ]


atom_feature_keys: [
'atom_atomic_numbers'
]

molecule_feature_keys : [
'molecule_num_atoms'
]
