#First, define the dataset by a series of conditions in format [key, type, [elements]]
#where type is in not_in or range and elements are [min, max], or a list of discrete values
#
#Then, specify the features which will be fed to models in training

seed: 1
max_dataset_length: 1000000
save_dataset: False
dataset_type: 'crystal'
regression_target: 'crystal_reduced_volume' # 'crystal_cell_volume' 'crystal_density' 'crystal_packing_coefficient'
single_molecule_dataset_identifier: null
test_fraction: 0.2
filter_protons: False

filter_polymorphs: True
filter_duplicate_molecules: True
filter_conditions: [['crystal_z_prime','in', [1]],  # NOTE we can currently only process Z' == 1 in models
                    ['crystal_symmetry_operations_are_nonstandard','in',[False]],
                    ['max_atomic_number','range',[1,100]],
                    ['molecule_num_atoms','range',[3,100]],
                    #['molecule_radius','range',[1,5]],
                    ['asymmetric_unit_is_well_defined','in',[True]],
                    ['reduced_volume_fraction', 'range',[0.75, 1.15]],
                    #['crystal_space_group_number','in',[2,14,19]]
                    ]
